#!/usr/bin/env bash
# let’s install one

sudo su
apt-get update
apt-get -y install nginx
ufw allow "Nginx HHTP"
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server_name_;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
