#!/usr/bin/env bash
# HAproxy configuration

sudo apt upgrade -y
sudo apt-get install -y haproxy=2.5.\*

printf %s "
frontend http_front
    bind *: 80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 2787-web-01 35.231.108.125 check
    server 2787-web-02 34.75.97.188 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
