#!/usr/bin/env bash
#Bash script that displays the time

i=1
j=0
while [[ $j -lt 13 ]]
do
     echo "Hour: $j";
     while [[ $i -le 59 ]]
     do
	 echo $i
	 i=$((i+1))
     done
     i="1"
       j=$((j+1))
    done
