#!/usr/bin/env bash

#  get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.

#sudoservice apache2 restart
# apache2: unrecognized service
# service httpd restart
